/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package belajar.kotlin.unit.test

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.*

//dhfdhfjdfd
class AppTest {
    // Deklarasi kelas bernama AppTest untuk menguji fungsionalitas kelas App.

    @Test
    // Anotasi yang menandakan bahwa fungsi ini adalah sebuah unit test.
    fun testAppHasAGreeting() {
        // Fungsi testAppHasAGreeting untuk memeriksa apakah kelas App memiliki pesan salam (greeting).
        println("Ini Test")
        // Mencetak pesan "Ini Test" ke konsol.

        val classUnderTest = App()
        // Membuat instance dari kelas App dan menyimpannya dalam variabel 'classUnderTest'.

        assertNotNull(classUnderTest.greeting, "should have a greeting")
        // Memastikan bahwa properti 'greeting' dari kelas 'App' tidak bernilai null. Jika bernilai null, akan menampilkan pesan kesalahan "should have a greeting".
    }
}

